name: Environment Variables
on: [push]

env:
    WF_LEVEL_ENV: Available for all jobs

jobs:
    env-vars-and-context:
        runs-on: ubuntu-latest
        if: github.ref == 'refs/heads/main'
        env:
            JOB_LEVEL_ENV: Available for this job
        steps:
            # Evaluated in the runner machine
            - name: log ENV VAR
              run: echo $GITHUB_REF
            # Gets sent evaluated to the runner machine
            - name: Log Context
              run: echo '${{ github.ref }}'
            - name: Set Env Var
              run: |
                echo "NEW_ENV_VAR=$(date)" >> "$GITHUB_ENV"
                echo "JOB_LEVEL_ENV=$RANDOM" >> "$GITHUB_ENV"
            - name: Multiline ENV VAR
                # Dynamic environment variables
              run: |
                DELIMITER=$(dd if=/dev/urandom bs=15 count=1 status=none | base64)
                echo "RANDOM_JOKE<<$DELIMITER" >> "$GITHUB_ENV"
                echo "Here is a joke: " >> "$GITHUB_ENV"
                curl -s https://icanhazdadjoke.com/ >> "$GITHUB_ENV"
                echo "" >> "$GITHUB_ENV"
                echo "$DELIMITER" >> "$GITHUB_ENV"
            - name: Log Custom ENV Vars
              env:
                STEP_LEVEL_ENV: Available for this step
                WF_LEVEL_ENV: Overriden WF ENV in Step
              run: |
                echo '${{ env.STEP_LEVEL_ENV }}'
                echo $WF_LEVEL_ENV
                echo $JOB_LEVEL_ENV
                echo $NEW_ENV_VAR
                echo $RANDOM_JOKE